---

# == Notes ==

# - GitLab automatically passes artifacts from previous stages by default
# - Set required secret variables at: https://gitlab.data.bas.ac.uk/MAGIC/web-map-inventory/-/settings/ci_cd

# = Secret variables
#   Variables are grouped by section in KEY: "value" format (e.g. FOO: "bar")
#   Where a variable should be protected (only accessible to the master branch, tags, its name is appended with
#     '(protected)' (e.g. FOO (protected)`
#   Where a variable is a file, it's name is appended with '(file)' and the value refers to the file that should be
#     used as it's contents (e.g. FOO (file): "[contents of ./bar]"
#   Sensitive values are represented by "[Sensitive]"
#
# - App
# > DOT_ENV (protected, file): "[contents of .env]"
# > DOT_FLASKENV (protected, file): "[contents of .flaskenv]"
#
# - PyPi (production) - create tokens at https://pypi.org/manage/account/
# > PYPI_TOKEN (protected): "[Sensitive]"
#
# - PyPi (staging) - create tokens at https://test.pypi.org/manage/account/
# > PYPI_TEST_TOKEN (protected): "[Sensitive]"
#
# - Sentry
# > SENTRY_AUTH_TOKEN: "[Sensetive]"
# > SENTRY_DSN: "[Sensetive]"
#
# - Deployment
# > SSH_PRIVATE_KEY (protected, file): "[contents of BAS MAGIC Shared Deployment Identity private key]"

# == Global settings ==

stages:
  - ðŸ§ª test
  - ðŸšš publish
  - ðŸ— build
  - ðŸš€ release

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_CERT_PATH: /certs/client
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_VERIFY: 1
  GITLAB_REGISTRY: docker-registry.data.bas.ac.uk
  APP_NAME: magic-map-layers-airflow
  APP_PACKAGE: bas-web-map-inventory
  APP_MODULE: bas_web_map_inventory
  SENTRY_ORG: antarctica
  SENTRY_PROJECT: web-map-inventory
  DEPLOY_USER: geoweb
  DEPLOY_HOST: bslws01.nerc-bas.ac.uk

image:
  name: docker-registry.data.bas.ac.uk/magic/web-map-inventory:latest
  entrypoint: [""]

# == Jobs ==

test-app:
  stage: ðŸ§ª test
  variables:
    FLASK_ENV: testing
  before_script:
    - "touch .env"
    - "mkdir -p /usr/src/app/bas_web_map_inventory/resources/xml_schemas/"
    - "cp -a --no-preserve=mode,ownership bas_web_map_inventory/resources/xml_schemas/*.xsd /usr/src/app/bas_web_map_inventory/resources/xml_schemas/"
  script:
    - "pytest -o junit_family=xunit2 --junitxml=test-results.xml --random-order"
  artifacts:
    reports:
      junit: test-results.xml

coverage-app:
  stage: ðŸ§ª test
  variables:
    FLASK_ENV: testing
  before_script:
    - "touch .env"
    - "mkdir -p /usr/src/app/bas_web_map_inventory/resources/xml_schemas/"
    - "cp -a --no-preserve=mode,ownership bas_web_map_inventory/resources/xml_schemas/*.xsd /usr/src/app/bas_web_map_inventory/resources/xml_schemas/"
  script:
    - "pytest --cov=bas_web_map_inventory --cov-fail-under=100 ."
    - "coverage html"
  artifacts:
    name: "$CI_BUILD_TOKEN-coverage"
    paths:
      - htmlcov
    expire_in: 1 month

typehints-app:
  stage: ðŸ§ª test
  script:
    - "mypy --junit-xml typehint-results.xml bas_web_map_inventory/"
  artifacts:
    reports:
      junit: typehint-results.xml

pep8-app:
  stage: ðŸ§ª test
  script:
    - "black --check bas_web_map_inventory/"

bandit-app:
  stage: ðŸ§ª test
  script:
    - "bandit -r ."

publish-app-stage:
  stage: ðŸšš publish
  before_script:
    - "poetry config pypi-token.pypi-testing $PYPI_TEST_TOKEN --local"
    - "python support/python-packaging/parse_version.py $(git describe --tags) --pyproject"
  script:
    - "poetry publish --build --repository pypi-testing --no-interaction"
  artifacts:
    name: "$CI_BUILD_TOKEN-build"
    paths:
      - dist
    expire_in: 1 month
  only:
    - master

publish-app-prod:
  stage: ðŸšš publish
  before_script:
    - "poetry config pypi-token.pypi $PYPI_TOKEN --local"
    - "python support/python-packaging/parse_version.py $(git describe --tags) --pyproject"
  script:
    - "poetry publish --build --repository pypi --no-interaction"
  artifacts:
    name: "$CI_BUILD_TOKEN-build"
    paths:
      - dist
    expire_in: 1 month
  only:
    - tags

build-dev:
  stage: ðŸ— build
  script:
    - 'poetry build'
  artifacts:
    name: "$CI_BUILD_TOKEN-build"
    paths:
      - dist
    expire_in: 1 week
  except:
    - master
    - tags

build-stage:
  stage: ðŸ— build
  image:
    name: docker:19.03-dind
    entrypoint: [""]
  before_script:
    - "apk update && apk add python3 git"
    - "python3 support/python-packaging/parse_version.py $(git describe --tags) > _version && export VERSION=$(cat _version)"
    - "export PACKAGE_VERSION=$APP_PACKAGE==$VERSION"
    - "cp $DOT_ENV provisioning/docker/.env"
    - "cp $DOT_FLASKENV provisioning/docker/.flaskenv"
    - "mkdir -p provisioning/docker/wheelhouse"
    - "cp dist/*.whl provisioning/docker/wheelhouse"
  script:
    - 'cd provisioning/docker'
    - 'echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin'
    - 'docker build . -t $CI_REGISTRY_IMAGE/deploy:latest --build-arg PACKAGE_VERSION=$PACKAGE_VERSION'
    - 'docker push $CI_REGISTRY_IMAGE/deploy:latest'
  services:
    - docker:dind
  tags:
    - dnd
  only:
    - master

build-prod:
  stage: ðŸ— build
  image:
    name: docker:19.03-dind
    entrypoint: [""]
  before_script:
    - "apk update && apk add python3 git"
    - "python3 support/python-packaging/parse_version.py $(git describe --tags) > _version && export VERSION=$(cat _version)"
    - "export PACKAGE_VERSION=$APP_PACKAGE==$VERSION"
    - "cp $DOT_ENV provisioning/docker/.env"
    - "cp $DOT_FLASKENV provisioning/docker/.flaskenv"
    - "mkdir -p provisioning/docker/wheelhouse"
    - "cp dist/*.whl provisioning/docker/wheelhouse"
  script:
    - 'cd provisioning/docker'
    - 'echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin'
    - 'docker build . -t $CI_REGISTRY_IMAGE/deploy:stable -t $CI_REGISTRY_IMAGE/deploy:$VERSION --build-arg PACKAGE_VERSION=$PACKAGE_VERSION'
    - 'docker push $CI_REGISTRY_IMAGE/deploy:stable'
    - 'docker push $CI_REGISTRY_IMAGE/deploy:$VERSION'
  services:
    - docker:dind
  tags:
    - dnd
  only:
    - tags

release-stage:
    stage: ðŸš€ release
    image:
      name: alpine:latest
      entrypoint: [""]
    before_script:
      - 'apk update && apk add openssh-client'
      - "mkdir -p /root/.ssh"
      - "mv $SSH_PRIVATE_KEY ~/.ssh/id_rsa"
      - "chmod 400 ~/.ssh/id_rsa"
      - "ssh-keyscan $DEPLOY_HOST > ~/.ssh/known_hosts"
    script:
      - "ssh $DEPLOY_USER@$DEPLOY_HOST podman pull $CI_REGISTRY_IMAGE/deploy:latest"
    only:
     - master
    environment:
      name: Staging

release-prod:
  stage: ðŸš€ release
  image:
    name: alpine:latest
    entrypoint: [""]
  before_script:
    - 'apk update && apk add openssh-client'
    - "mkdir -p /root/.ssh"
    - "mv $SSH_PRIVATE_KEY ~/.ssh/id_rsa"
    - "chmod 400 ~/.ssh/id_rsa"
    - "ssh-keyscan $DEPLOY_HOST > ~/.ssh/known_hosts"
  script:
    - "ssh $DEPLOY_USER@$DEPLOY_HOST podman pull $CI_REGISTRY_IMAGE/deploy:stable"
  only:
   - tags
  environment:
    name: Production

sentry-stage:
  stage: ðŸš€ release
  image:
    name: getsentry/sentry-cli
    entrypoint: [""]
  before_script:
    - 'apk update && apk add python3 git'
    - "python3 support/python-packaging/parse_version.py $(git describe --tags) > _version && export VERSION=$(cat _version)"
    - "export SENTRY_VERSION=$SENTRY_PROJECT@$VERSION"
  script:
    - "sentry-cli releases new --finalize $SENTRY_VERSION"
    - "sentry-cli releases deploys $SENTRY_VERSION new -e staging"
    - "sentry-cli releases set-commits --auto $SENTRY_VERSION"
  only:
    - master

sentry-prod:
  stage: ðŸš€ release
  image:
    name: getsentry/sentry-cli
    entrypoint: [""]
  before_script:
    - 'apk update && apk add python3 git'
    - "python3 support/python-packaging/parse_version.py $(git describe --tags) > _version && export VERSION=$(cat _version)"
    - "export SENTRY_VERSION=$SENTRY_PROJECT@$VERSION"
  script:
    - "sentry-cli releases new --finalize $SENTRY_VERSION"
    - "sentry-cli releases deploys $SENTRY_VERSION new -e production"
    - "sentry-cli releases set-commits --auto $SENTRY_VERSION"
  only:
    - tags
